U5-W4-BuildWeek/Controllers/TipologiaAnimaleController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using U5_W4_BuildWeek.Models.DbModels;

namespace U5_W4_BuildWeek.Controllers
{
    [Authorize(Roles = "Admin,Veterinario")]
    public class TipologiaAnimaleController : Controller
    {
        ModelDbContext db = new ModelDbContext();

        public ActionResult Tipologie()
        {
            var tipologie = db.AnimaliTipologia.ToList();
            return View(tipologie);
        }

        [HttpGet]
        public ActionResult AggiungiTipologia()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AggiungiTipologia(AnimaliTipologia nuovaTipologia)
        {
            if (ModelState.IsValid)
            {
                db.AnimaliTipologia.Add(nuovaTipologia);
                db.SaveChanges();
                return RedirectToAction("Tipologie");
            }
            return View();
        }

        [HttpGet]
        public ActionResult ModificaTipologia(int id)
        {
            var tipologia = db.AnimaliTipologia.Find(id);
            return View(tipologia);
        }

        [HttpPost]
        public ActionResult ModificaTipologia(AnimaliTipologia nuovaTipologia)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nuovaTipologia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Tipologie");
            }
            return View();
        }

        public ActionResult EliminaTipologia(int id)
        {
            var tipologia = db.AnimaliTipologia.Find(id);

            if (tipologia != null)
            {
                //Trovo gli animali di quella tipologia e li cancello
                List<Animali> Animali = db.Animali.Where(x => x.FkTipologia == id).ToList();
                foreach (Animali animale in Animali)
                    db.Animali.Remove(animale);

                db.AnimaliTipologia.Remove(tipologia);
                db.SaveChanges();
            }
            return RedirectToAction("Tipologie");
        }
    }
}

U5-W4-BuildWeek/Views/TipologiaAnimale/AggiungiTipologia.cshtml
@model U5_W4_BuildWeek.Models.DbModels.AnimaliTipologia

@{
    ViewBag.Title = "AggiungiTipologia";
}

<h2 class="titolo">Aggiungi tipologia</h2>

<div class="wrapper fadeInDown">


    @using (Html.BeginForm("AggiungiTipologia", "TipologiaAnimale", FormMethod.Post, new { id = "formContent", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <p><span class="star">* </span>CAMPI RICHIESTI</p>

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label for="Tipologia" class="label-form">@Html.Raw("<strong>Tipologia</strong><span class='star'> *</span>")</label>
                @Html.TextBoxFor(model => model.Tipologia)
                @Html.ValidationMessageFor(model => model.Tipologia, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <div >
                    <input type="submit" value="Aggiungi" class="btn btn-primary my-3" />
                </div>
            </div>
        </div>
    }

</div>

U5-W4-BuildWeek/Views/TipologiaAnimale/ModificaTipologia.cshtml
@model U5_W4_BuildWeek.Models.DbModels.AnimaliTipologia


@{
    ViewBag.Title = "ModificaTipologia";
}

<h2 class="titolo">Modifica @Model.Tipologia </h2>

<div class="wrapper fadeInDown">


    @using (Html.BeginForm("ModificaTipologia", "TipologiaAnimale", FormMethod.Post, new { id = "formContent", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <p><span class="star">* </span>CAMPI RICHIESTI</p>

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label for="Tipologia" class="label-form">@Html.Raw("<strong>Tipologia</strong><span class='star'> *</span>")</label>
                @Html.TextBoxFor(model => model.Tipologia)
                @Html.ValidationMessageFor(model => model.Tipologia, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <div class="">
                    <input type="submit" value="Modifica" class="btn btn-primary my-3" />
                </div>
            </div>
        </div>
    }

</div>

U5-W4-BuildWeek/Views/TipologiaAnimale/Tipologie.cshtml
@model IEnumerable<U5_W4_BuildWeek.Models.DbModels.AnimaliTipologia>

@{
    ViewBag.Title = "Tipologie";
}




<div class="table-container">
    <div class="aggiungi">
        <a href="@Url.Action("AggiungiTipologia")"><i class="fa-regular fa-square-plus add-icon"></i></a>
    </div>

    <div class="table-animali w-25">
        <div class="header">Registro Tipologie</div>

        <table>
            <tr>
                <th></th>
      
                <th>Tipologia</th>
              
          
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                           
                    <td>
                        @Html.DisplayFor(modelItem => item.Tipologia)
                    </td>
                    <td>
                        <a href="@Url.Action("ModificaTipologia", new { id = item.Id })"><i class="fa-solid fa-pencil table-icon"></i></a>
                     
                        <a href="@Url.Action("EliminaTipologia", new { id = item.Id })"><i class="fa-solid fa-trash-can table-icon"></i></a>

                   
                    </td>
             
                </tr>
            }
        </table>
    </div>
    <div class="pb-5"></div>
</div>