U5-W4-BuildWeek/Models/DbModels/Animali.cs
namespace U5_W4_BuildWeek.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Web;

    [Table("Animali")]
    public partial class Animali
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animali()
        {
            Ricoveri = new HashSet<Ricoveri>();
            Visite = new HashSet<Visite>();
        }

        public int Id { get; set; }

        public DateTime DataRegistrazione { get; set; }

        public DateTime? DataInizioRicovero { get; set; }

        [DefaultValue(false)]
        public bool RicoveroAttivo { get; set; }

        [Required]
        [StringLength(70)]
        public string Nome { get; set; }

        [StringLength(50)]
        public string Foto { get; set; }

        [NotMapped]
        public HttpPostedFileBase FotoFile { get; set; }

        [Required]
        [StringLength(50)]
        public string Colore { get; set; }

        public DateTime? DataNascita { get; set; }

        [StringLength(50)]
        public string Microchip { get; set; }

        public int FkTipologia { get; set; }

        public int? FkUtente { get; set; }

        public virtual AnimaliTipologia AnimaliTipologia { get; set; }

        public virtual Utenti Utenti { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ricoveri> Ricoveri { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visite> Visite { get; set; }
    }
}

U5-W4-BuildWeek/Controllers/AnimaliController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using U5_W4_BuildWeek.Models.DbModels;

namespace U5_W4_BuildWeek.Controllers
{
    [Authorize(Roles = "Admin,Veterinario")]
    public class AnimaliController : Controller
    {
        ModelDbContext db = new ModelDbContext();

        public ActionResult Index()
        {
            return View(db.Animali.ToList());
        }


        [AllowAnonymous]
        public ActionResult DettaglioAnimale(int id)
        {
            var animale = db.Animali.Find(id);
            return View(animale);
        }

        [AllowAnonymous]
        public PartialViewResult StoriaMedica(int id)
        {
            ViewBag.Id = id;
            return PartialView(db.Visite.Where(v => v.FkAnimale == id).OrderByDescending(o => o.DataVisita));
        }


        [HttpGet]
        public ActionResult RegistraAnimale()
        {
            ViewBag.TipologieAnimali = GetTipologiaAnimale;
            ViewBag.Clienti = GetListaClienti;
            return View();
        }

        [HttpPost]
        public ActionResult RegistraAnimale(Animali animale)
        {
            ViewBag.TipologieAnimali = GetTipologiaAnimale;
            ViewBag.Clienti = GetListaClienti;

            if (ModelState.IsValid)
            {
                if (animale.FotoFile != null && animale.FotoFile.ContentLength > 0)
                {
                    var path = Path.Combine(Server.MapPath("~/Content/Imgs/Animali/"), animale.FotoFile.FileName);
                    animale.FotoFile.SaveAs(path);

                    animale.Foto = animale.FotoFile.FileName;
                }
                animale.DataRegistrazione = DateTime.Today;

                animale.RicoveroAttivo = animale.DataInizioRicovero != null ? true : false;

                db.Animali.Add(animale);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }
            return View();
        }

        [HttpGet]
        public ActionResult ModificaAnimale(int id)
        {
            ViewBag.TipologieAnimali = GetTipologiaAnimale;
            ViewBag.Clienti = GetListaClienti;
            var animale = db.Animali.Find(id);
            return View(animale);
            
        }

        [HttpPost]
        public ActionResult ModificaAnimale(Animali animale)
        {
            ViewBag.TipologieAnimali = GetTipologiaAnimale;
            ViewBag.Clienti = GetListaClienti;

            if (ModelState.IsValid)
            {
                if (animale.FotoFile != null && animale.FotoFile.ContentLength > 0)
                {
                    var path = Path.Combine(Server.MapPath("~/Content/Imgs/Animali/"), animale.FotoFile.FileName);
                    animale.FotoFile.SaveAs(path);

                    animale.Foto = animale.FotoFile.FileName;
                }
                if (animale.DataInizioRicovero != null)
                {
                    animale.RicoveroAttivo = true;
                }
                db.Entry(animale).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(animale);
        }


        public ActionResult EliminaAnimale(int id)
        {
            Animali animale = db.Animali.Find(id);
            if (animale != null)
            {
                //Elmino tutte le visite
                List<Visite> visite = db.Visite.Where(v => v.FkAnimale == id).ToList();
                foreach(Visite visita in visite)
                    db.Visite.Remove(visita);

                db.Animali.Remove(animale);
                db.SaveChanges();
            }
            return RedirectToAction("View");
        }


        [AllowAnonymous]
        [Authorize]
        public ActionResult Adotta(int id)
        {
            int utente = db.Utenti.Where(u => u.Username == User.Identity.Name).FirstOrDefault().Id;
            Animali animale = db.Animali.Find(id);

            animale.RicoveroAttivo = false;
            animale.FkUtente = utente;
            db.Entry(animale).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("DettaglioAnimale", new { id = id });
        }

        #region Get Clienti / Tipologie

        public List<SelectListItem> GetListaClienti
        {
            get
            {
                List<SelectListItem> Utenti = new List<SelectListItem>();
                List<Utenti> ListaUtenti = db.Utenti.ToList();

                foreach (Utenti utente in ListaUtenti)
                {
                    SelectListItem item = new SelectListItem { Text = utente.Nome, Value = utente.Id.ToString() };
                    Utenti.Add(item);
                }
                return Utenti;
            }
        }

        public List<SelectListItem> GetTipologiaAnimale
        {
            get
            {
                List<SelectListItem> TipologiaAnimali = new List<SelectListItem>();
                List<AnimaliTipologia> ListaAnimali = db.AnimaliTipologia.ToList();

                foreach (AnimaliTipologia animale in ListaAnimali)
                {
                    SelectListItem item = new SelectListItem { Text = animale.Tipologia, Value = animale.Id.ToString() };
                    TipologiaAnimali.Add(item);
                }
                return TipologiaAnimali;
            }
        }

        #endregion
    }
}

U5-W4-BuildWeek/Controllers/VisiteController.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using U5_W4_BuildWeek.Models.DbModels;

namespace U5_W4_BuildWeek.Controllers
{
    [Authorize(Roles = "Admin,Veterinario")]
    public class VisiteController : Controller
    {
        ModelDbContext db = new ModelDbContext();
        // GET: Visite
        public ActionResult Index([Bind(Include = "Microchip,Nome")] Animali animale)
        {
            List<Visite> Visite = db.Visite.ToList();

            if (animale.Microchip != null)
                Visite = Visite.Where(v => v.Animali.Microchip == animale.Microchip.Trim()).ToList();

            if (animale.Nome != null)
                Visite = Visite.Where(v => v.Animali.Nome.ToLower().Contains(animale.Nome.ToLower())).ToList();

            return View(Visite);
        }

        public ActionResult Create(int id)
        {
            ViewBag.Id = id;
            return View();
        }

        [HttpPost]
        public ActionResult Create(Visite visite)
        {

            if (ModelState.IsValid)
            {
                db.Visite.Add(visite);
                db.SaveChanges();
                return RedirectToAction("DettaglioAnimale", "Animali", new{ id = visite.FkAnimale });
            }

            ViewBag.Id = visite.FkAnimale;
            return View(visite);      
        }


        public ActionResult Edit(int id)
        {
            return View(db.Visite.Find(id));
        }

        [HttpPost]
        public ActionResult Edit(Visite visita)
        {
            if (ModelState.IsValid) 
            {
                db.Entry(visita).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View();
        }


        public ActionResult Delete(int id) 
        {
            Visite visite = db.Visite.Find(id);
            db.Visite.Remove(visite);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

U5-W4-BuildWeek/Views/Animali/DettaglioAnimale.cshtml
@model U5_W4_BuildWeek.Models.DbModels.Animali

@{
    ViewBag.Title = "DettaglioAnimale";
}

<h1 class="m-3">
    <i class="fa fa-paw" aria-hidden="true"></i>
    @Model.Nome
</h1>

<div class="p-3 px-5 table-container">
    <div class="row align-items-center rounded" style="background-color: rgb(255, 255, 255, 0.92); ">
        <div class="col-12 col-md-4">
            <img src="~/Content/Imgs/Animali/@Model.Foto" class="w-100" />
        </div>

        @* Info *@
        <div class="col-12 col-md-8 ml-5 fs-5">

            <div class="row row-cols-1 row-cols-2 mx-4 mb-4">

                @* Padrone *@
                <div>
                    <div class="fw-bold">
                        Padrone
                    </div>
                    <div>
                        @if (Model.FkUtente != null)
                        {
                            @Html.DisplayFor(model => model.Utenti.Nome)
                        }
                        else
                        {
                            if (Model.RicoveroAttivo && User.Identity.IsAuthenticated)
                            {
                                <span> Questo animale non ha un padrone, <a href="@Url.Action("Adotta", new { id = Model.Id })">adottalo!</a> </span>
                            }
                        }
                    </div>
                </div>

                @* Specie *@
                <div>
                    <div class="fw-bold">
                        Specie
                    </div>
                    <div>
                        @Html.DisplayFor(model => model.AnimaliTipologia.Tipologia)
                    </div>
                </div>

                @* Microchip *@
                <div>
                    <div class="fw-bold">
                        @Html.DisplayNameFor(model => model.Microchip)
                    </div>
                    <div>
                        @if (Model.Microchip == "" || Model.Microchip == null)
                        {
                            <span> Non presente </span>
                        }
                        else
                        {
                            @Html.DisplayFor(model => model.Microchip)
                        }
                    </div>
                </div>

                @* Colore *@
                <div>
                    <div class="fw-bold">
                        @Html.DisplayNameFor(model => model.Colore)
                    </div>
                    <div>
                        @Html.DisplayFor(model => model.Colore)
                    </div>
                </div>
            </div>

            <div class="row row-cols-1 row-cols-2 mx-4 mb-4">

                @* Registrazione *@
                <div>
                    <div class="fw-bold">
                        Data di registrazione
                    </div>
                    <div>
                        @Html.DisplayFor(model => model.DataRegistrazione)
                    </div>
                </div>

                @* Nascita *@
                <div>
                    <div class="fw-bold">
                        Data di nascita (o presunta)
                    </div>
                    <div>
                        @Html.DisplayFor(model => model.DataNascita.Value)
                    </div>
                </div>

                @* Ricovero *@
                @if (Model.DataInizioRicovero != null)
                {
                    <div>
                        <div class="fw-bold">
                            Data inizio ricovero
                        </div>
                        <div>
                            @Html.DisplayFor(model => model.DataInizioRicovero)
                        </div>
                    </div>
                }




            </div>

        </div>
    </div>
    @* Foto *@

</div>







@{Html.RenderAction("StoriaMedica", new {id=Model.Id});}

U5-W4-BuildWeek/Views/Animali/Index.cshtml
@model IEnumerable<U5_W4_BuildWeek.Models.DbModels.Animali>


<div class="table-container">
    <div class="aggiungi">
        <a href="@Url.Action("RegistraAnimale")"><i class="fa-regular fa-square-plus add-icon"></i></a>
    </div>

    <div class="table-animali">
        <div class="header">Registro animali</div>

        <table>
            <tr>
                <th></th>
                <th>Registrazione</th>
                <th>Ricovero</th>
                <th>Tipo</th>
                <th>Nome</th>
                <th>Colore</th>
                <th>Data di nascita</th>
                <th>Microchip</th>
                <th>Proprietario</th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <img src="~/Content/Imgs/Animali/@item.Foto" alt="photo" class="animal-picture" />
                    </td>
                    <td>
                        <p>@item.DataRegistrazione.ToShortDateString()</p>
                    </td>
                    <td>
                        @if (item.DataInizioRicovero != null)
                        {
                            <p style='@if (!item.RicoveroAttivo) { @Html.Raw("color: lightgray !important"); }'>
                                @item.DataInizioRicovero.Value.ToShortDateString()
                            </p>
                        }
                        else
                        {
                            <p> - </p>
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AnimaliTipologia.Tipologia)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Colore)
                    </td>
                    <td>
                        <p>@(item.DataNascita != null ? item.DataNascita.Value.ToShortDateString() : "-")</p>
                    </td>
                    <td>
                        <p>@(item.Microchip != null ? item.Microchip : "-")</p>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Utenti.Nome)
                    </td>
                    <td>
                        <a href="@Url.Action("ModificaAnimale", new { id = item.Id })"><i class="fa-solid fa-pencil table-icon"></i></a>
                        <a href="@Url.Action("DettaglioAnimale", new { id = item.Id })"><i class="fa-solid fa-magnifying-glass table-icon"></i></a>
                        <a href="@Url.Action("EliminaAnimale", new { id = item.Id })"><i class="fa-solid fa-trash-can table-icon"></i></a>
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="pb-5"></div>
</div>

U5-W4-BuildWeek/Views/Animali/ModificaAnimale.cshtml
@model U5_W4_BuildWeek.Models.DbModels.Animali

@{
    ViewBag.Title = "ModificaAnimale";
}

<section class="form-container">
    <h2 class="titolo">Modifica Animale</h2>

    <div class="wrapper fadeInDown">


        @using (Html.BeginForm("ModificaAnimale", "Animali", FormMethod.Post, new { id = "formContent", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.DataRegistrazione)

                <p><span class="star">* </span>CAMPI RICHIESTI</p>

                <div class="form-group">
                    <label for="DataRegistrazione" class="label-form">@Html.Raw("<strong>Data registrazione</strong>")</label>
                    <input class="form-control" type="text" value="@Model.DataRegistrazione.ToShortDateString()" readonly />
                    @Html.ValidationMessageFor(model => model.DataInizioRicovero, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label for="DataInizioRicovero" class="label-form">@Html.Raw("<strong>Data inizio ricovero</strong>")</label>
                    @Html.TextBoxFor(model => model.DataInizioRicovero, "{0:yyyy-MM-dd}", new { type = "date" })
                    @Html.ValidationMessageFor(model => model.DataInizioRicovero, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label for="Nome" class="label-form">@Html.Raw("<strong>Nome</strong><span class='star'> *</span>")</label>
                    @Html.EditorFor(model => model.Nome)
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label for="FotoFile" class="label-form">@Html.Raw("<strong>Foto</strong>")</label>
                    <input type="file" name="FotoFile" />
                    @Html.ValidationMessageFor(model => model.FotoFile, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label for="Colore" class="label-form">@Html.Raw("<strong>Colore</strong><span class='star'> *</span>")</label>
                    @Html.EditorFor(model => model.Colore, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Colore, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label for="DataNascita" class="label-form">@Html.Raw("<strong>Data di nascita</strong>")</label>
                    @Html.TextBoxFor(model => model.DataNascita, "{0:yyyy-MM-dd}", new { type = "date" })
                    @Html.ValidationMessageFor(model => model.DataNascita, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label for="Microchip" class="label-form">@Html.Raw("<strong>Numero microchip</strong>")</label>
                    @Html.EditorFor(model => model.Microchip, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Microchip, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label for="FkTipologia" class="label-form">@Html.Raw("<strong>Tipologia</strong><span class='star'> *</span>")</label>
                    @Html.DropDownListFor(model => model.FkTipologia, new SelectList(ViewBag.TipologieAnimali, "Value", "Text"), "Seleziona tipologia", new { htmlAttributes = new { @class = "form-control dropdown-menu" } })
                    @Html.ValidationMessageFor(model => model.FkTipologia, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label for="FkUtente" class="label-form">@Html.Raw("<strong>Proprietario</strong>")</label>
                    @Html.DropDownListFor(model => model.FkUtente, new SelectList(ViewBag.Clienti, "Value", "Text"), "Seleziona Proprietario", new { htmlAttributes = new { @class = "form-control dropdown-menu" } })
                    @Html.ValidationMessageFor(model => model.FkUtente, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <input type="submit" value="Modifica" class="btn btn-default" />
                </div>
            </div>
        }

    </div>

</section>

U5-W4-BuildWeek/Views/Animali/RegistraAnimale.cshtml
@model U5_W4_BuildWeek.Models.DbModels.Animali

<section class="form-container">

    <h2 class="titolo">Registra Animale</h2>

    <div class="wrapper fadeInDown">

        @using (Html.BeginForm("RegistraAnimale", "Animali", FormMethod.Post, new { id = "formContent", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <p><span class="star">* </span>CAMPI RICHIESTI</p>

            <div class="form-group">
                <label for="DataInizioRicovero" class="label-form">@Html.Raw("<strong>Data inizio ricovero</strong>")</label>
                @Html.TextBoxFor(model => model.DataInizioRicovero, "{0:yyyy-MM-dd}", new { type = "date" })
                @Html.ValidationMessageFor(model => model.DataInizioRicovero, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label for="Nome" class="label-form">@Html.Raw("<strong>Nome</strong><span class='star'> *</span>")</label>
                @Html.EditorFor(model => model.Nome)
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label for="FotoFile" class="label-form">@Html.Raw("<strong>Foto</strong>")</label>
                <input type="file" name="FotoFile" />
                @Html.ValidationMessageFor(model => model.FotoFile, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label for="Colore" class="label-form">@Html.Raw("<strong>Colore</strong><span class='star'> *</span>")</label>
                @Html.EditorFor(model => model.Colore, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Colore, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label for="DataNascita" class="label-form">@Html.Raw("<strong>Data di nascita</strong>")</label>
                @Html.TextBoxFor(model => model.DataNascita, "{0:yyyy-MM-dd}", new { type = "date" })
                @Html.ValidationMessageFor(model => model.DataNascita, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label for="Microchip" class="label-form">@Html.Raw("<strong>Numero microchip</strong>")</label>
                @Html.EditorFor(model => model.Microchip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Microchip, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label for="FkTipologia" class="label-form">@Html.Raw("<strong>Tipologia</strong><span class='star'> *</span>")</label>
                @Html.DropDownListFor(model => model.FkTipologia, new SelectList(ViewBag.TipologieAnimali, "Value", "Text"), "Seleziona tipologia", new { htmlAttributes = new { @class = "form-control dropdown-menu" } })
                @Html.ValidationMessageFor(model => model.FkTipologia, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                <label for="FkUtente" class="label-form">@Html.Raw("<strong>Proprietario</strong>")</label>
                @Html.DropDownListFor(model => model.FkUtente, new SelectList(ViewBag.Clienti, "Value", "Text"), "Seleziona Proprietario", new { htmlAttributes = new { @class = "form-control dropdown-menu" } })
                @Html.ValidationMessageFor(model => model.FkUtente, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <input type="submit" value="Registra animale" class="btn btn-primary my-3" />
            </div>

            <div class="form-group">
                @Html.ActionLink("Torna indietro", "Index", null, new { @class = "backLink" })
            </div>
        }
    </div>
</section>

U5-W4-BuildWeek/Views/Animali/StoriaMedica.cshtml
@model IEnumerable<U5_W4_BuildWeek.Models.DbModels.Visite>

@{
    ViewBag.Title = "StoriaMedica";
}

<div style="background-color: rgba(86, 186, 237, 0.2)" class="p-3">


    <h2>
        <i class="fa fa-heartbeat" aria-hidden="true"></i>
        Storia medica
    </h2>

    <p class="btn btn-outline-dark ">
        <i class="fa-solid fa-plus"></i> @Html.ActionLink("Aggiungi visita", "Create", "Visite", new { area = "", id = @ViewBag.Id }, new { @class = "text-reset text-decoration-none" })
    </p>
    @if (Model.Count() > 0)
    {
        <table class="table p-3">
            <tr>
                <th>
                    Data visita
                </th>
                <th>
                    Esame
                </th>
                <th>
                    Descrizione
                </th>
                @if (User.IsInRole("Admin"))
                {
                    <th></th>
                }
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataVisita)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EsameObbiettivo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DescrizioneCura)
                    </td>
                    @if (User.IsInRole("Admin"))
                    {
                        <td>
                            <a href="@Url.Action("Edit", "Visite", new { area = "", id = item.Id })"><i class="fa-solid fa-pencil table-icon"></i></a>
                            <a href="@Url.Action("Delete", "Visite", new { area = "", id = item.Id })"><i class="fa-solid fa-trash-can table-icon"></i></a>
                        </td>
                    }
                </tr>
            }


        </table>

    }
    else
            {
                <p> Non c'è nulla qui... </p>
            }

</div>