U5-W4-BuildWeek/Controllers/RicoveriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using U5_W4_BuildWeek.Models;
using U5_W4_BuildWeek.Models.DbModels;

namespace U5_W4_BuildWeek.Controllers
{
    public class RicoveriController : Controller
    {

        ModelDbContext db = new ModelDbContext();

        public ActionResult Index()
        {
            ViewBag.Tipologie = db.AnimaliTipologia.ToList();
            return View();
        }


        public JsonResult RicoveriFilter(List<int> Tipologie)
        {
            List<RicoveriModel> ricoveri = new List<RicoveriModel>();
            List<Animali> animaliList = new List<Animali>();

            //Nel caso restituisca una lista null
            try
            {
                animaliList = db.Animali.Where(a => a.RicoveroAttivo && Tipologie.Contains(a.FkTipologia)).ToList();
            }
            catch { return Json(""); }

            if (animaliList.Count > 0)
                foreach (Animali animale in animaliList)
                    ricoveri.Add(new RicoveriModel
                    {
                        Id = animale.Id,
                        DataInizioRicovero = animale.DataInizioRicovero.Value.ToString(),
                        Nome = animale.Nome,
                        Foto = animale.Foto,
                        Colore = animale.Colore,
                        DataNascita = animale.DataNascita.HasValue ? animale.DataNascita.Value.ToString() : "-",
                        Microchip = animale.Microchip,
                        Tipologia = animale.AnimaliTipologia.Tipologia,
                    });

            return Json(ricoveri);
        }

        [Authorize(Roles = "Admin,Veterinario")]
        public JsonResult EstraiRicoveri()
        {
            List<RicoveriModel> ricoveri = new List<RicoveriModel>();
            List<Animali> animaliList = db.Animali.Where(a => a.RicoveroAttivo).ToList();
            foreach (Animali animale in animaliList)
                ricoveri.Add(new RicoveriModel
                {
                    Id = animale.Id,
                    DataInizioRicovero = animale.DataInizioRicovero.Value.ToString(),
                    Nome = animale.Nome,
                    Foto = animale.Foto,
                    Colore = animale.Colore,
                    DataNascita = animale.DataNascita.HasValue ? animale.DataNascita.Value.ToString() : "-",
                    Microchip = animale.Microchip,
                    Tipologia = animale.AnimaliTipologia.Tipologia,
                });

            return Json(ricoveri, JsonRequestBehavior.AllowGet);
        }


    }
}

U5-W4-BuildWeek/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="~/Content/StyleSheet1.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light p-3">
        <div id="divPrincipal" class="container-fluid d-flex justify-content-center">
            <div>
                @Html.ActionLink("Paws and Claws", "Index", "Home", new { area = "" }, new { @class = "navbar-brand m-0" })
            </div>
            <button id="menuButton" class="navbar-toggler d-block" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebar" aria-controls="sidebar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="offcanvas offcanvas-start" tabindex="-1" id="sidebar">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title">Menu</h5>
                    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div id="bodyMenu" class="offcanvas-body d-flex justify-content-center">
                    <div class="offcanvas-body" style="margin-left: auto">
                        <ul id="navy" class="navbar-nav">
                            @* Tutti tranne i farmacisti *@
                            @if (!User.IsInRole("Farmacista"))
                            {
                                <li class="nav-item me-3 active">
                                    @Html.ActionLink("Ricoveri Attivi", "Index", "Ricoveri", new { area = "" }, new { @class = "nav-link" })
                                </li>
                            }

                            @* Users o utenti non loggati *@
                            @if (User.IsInRole("User") || !User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item me-3 active">
                                    @Html.ActionLink("Cerca Animale", "CercaAnimale", "Home", new { area = "" }, new { @class = "nav-link" })
                                </li>
                            }

                            @* Qualsiasi altro ruolo che non sia user *@
                            else
                            {
                                @* Solo Veterinari / Admin *@
                                if (User.IsInRole("Veterinario") || User.IsInRole("Admin"))
                                {
                                    <li class="nav-item me-3 active">
                                        @Html.ActionLink("Animali", "Index", "Animali", new { area = "" }, new { @class = "nav-link" })
                                    </li>

                                    <li class="nav-item me-3 active">
                                        @Html.ActionLink("Visite", "Index", "Visite", new { area = "" }, new { @class = "nav-link" })
                                    </li>
                                }

                                @* Solo Farmacisti / Admin *@
                                if (User.IsInRole("Farmacista") || User.IsInRole("Admin"))
                                {
                                    <li class="nav-item me-3 active">
                                        @Html.ActionLink("Farmacia", "Index", "Farmacia", new { area = "" }, new { @class = "nav-link" })
                                    </li>
                                    <li class="nav-item me-3 active">
                                        @Html.ActionLink("Medicinali", "Index", "Medicinali", new { area = "" }, new { @class = "nav-link" })
                                    </li>
                                }

                                @* Solo Admin *@
                                if (User.IsInRole("Admin"))
                                {
                                    <li class="nav-item me-3 active">
                                        @Html.ActionLink("Utenti", "Index", "Admin", new { area = "" }, new { @class = "nav-link" })
                                    </li>
                                }
                            }
                        </ul>
                    </div>
                    <hr />
                    <div class="offcanvas-body" style="margin-left: auto">
                        <ul class="navbar-nav flex-row">
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item me-3">
                                    @Html.ActionLink("Login", "Login", "Home", new { area = "" }, new { @class = "nav-link" })
                                </li>
                            }
                            else
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle d-flex justify-content-center align-items-center" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        <img src="https://mdbcdn.b-cdn.net/img/new/avatars/1.webp"
                                             class="rounded-circle mx-1"
                                             height="22"
                                             alt="Black and White Portrait of a Man"
                                             loading="lazy" />
                                        Ciao @User.Identity.Name
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Profilo", "Profilo", "Home", new { area = "" }, new { @class = "dropdown-item" })</li>
                                        <li><hr /></li>
                                        <li>@Html.ActionLink("Logout", "Logout", "Home", new { area = "" }, new { @class = "dropdown-item" })</li>
                                    </ul>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <div>
        @RenderBody()
        <footer class="text-center text-lg-start bg-light text-muted">
            @if (ViewContext.RouteData.Values["Controller"].ToString() == "Home" && ViewContext.RouteData.Values["Action"].ToString() == "Index")
            {
                <section id="body-form" class="d-flex justify-content-center">
                    <div class="contact-form">
                        <div class="contact-image">
                            <img src="https://image.ibb.co/kUagtU/rocket_contact.png" alt="rocket_contact" />
                        </div>
                        <form method="post">
                            <h3>Lasciaci un Messaggio</h3>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group mb-1">
                                        <input type="text" name="txtName" class="form-control" placeholder="Il tuo nome" value="" />
                                    </div>
                                    <div class="form-group mb-1">
                                        <input type="text" name="txtEmail" class="form-control" placeholder="La tua email" value="" />
                                    </div>
                                    <div class="form-group mb-1">
                                        <input type="text" name="txtPhone" class="form-control" placeholder="Oggetto" value="" />
                                    </div>
                                    <div class="form-group mb-1">
                                        <input type="submit" name="btnSubmit" class="btnContact" value="Invia" />
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <textarea name="txtMsg" class="form-control" placeholder="Il tuo messaggio" style="width: 100%; height: 150px;"></textarea>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </section>
            }
            <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
                <div class="me-5 d-none d-lg-block">
                    <span>Resta in contatto con noi sui social network:</span>
                </div>
                <div>
                    <a href="" class="me-4 text-reset">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a href="" class="me-4 text-reset">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a href="" class="me-4 text-reset">
                        <i class="fab fa-google"></i>
                    </a>
                    <a href="" class="me-4 text-reset">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a href="" class="me-4 text-reset">
                        <i class="fab fa-linkedin"></i>
                    </a>
                    <a href="" class="me-4 text-reset">
                        <i class="fab fa-github"></i>
                    </a>
                </div>
            </section>
            <section>
                <div class="container text-center text-md-start mt-5">
                    <div class="row mt-3">
                        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                            <h6 class="text-uppercase fw-bold mb-4">
                                <i class="fas fa-paw me-3"></i>Paws and Claws
                            </h6>
                            <p>
                                Qui puoi utilizzare righe e colonne per organizzare i contenuti del tuo footer. Lorem ipsum
                                dolor sit amet, consectetur adipisicing elit.
                            </p>
                        </div>
                        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                            <h6 class="text-uppercase fw-bold mb-4">
                                Servizi
                            </h6>
                            <p>
                                <a href="#!" class="text-reset">Visite veterinarie</a>
                            </p>
                            <p>
                                <a href="#!" class="text-reset">Chirurgia veterinaria</a>
                            </p>
                            <p>
                                <a href="#!" class="text-reset">Nutrizione animale</a>
                            </p>
                            <p>
                                <a href="#!" class="text-reset">Emergenze veterinarie</a>
                            </p>
                        </div>
                        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                            <h6 class="text-uppercase fw-bold mb-4">
                                Link Utili
                            </h6>
                            <p>
                                <a href="#!" class="text-reset">Tariffe</a>
                            </p>
                            <p>
                                <a href="#!" class="text-reset">Prenotazioni online</a>
                            </p>
                            <p>
                                <a href="#!" class="text-reset">Domande frequenti</a>
                            </p>
                            <p>
                                <a href="#!" class="text-reset">Contatti</a>
                            </p>
                        </div>
                        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                            <h6 class="text-uppercase fw-bold mb-4">Contatti</h6>
                            <p><i class="fas fa-home me-3"></i> Via degli Animali, 12345, Città degli Animali, PA</p>
                            <p>
                                <i class="fas fa-envelope me-3"></i>
                                info@aziendaveterinaria.com
                            </p>
                            <p><i class="fas fa-phone me-3"></i> +01 234 567 890</p>
                            <p><i class="fas fa-print me-3"></i> +01 234 567 891</p>
                        </div>
                    </div>
                </div>
            </section>
            <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
                © 2023 Copyright:
                <a class="text-reset fw-bold" href="#">Team 2</a>
            </div>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/a7f72890b8.js" crossorigin="anonymous"></script>